feat: adding shared-vpc support
DeimosCloud/terraform-google-openvpn pull request #20
Opened 2022-10-21 10:14 UTC by adrianovs

2022-11-08 23:25 UTC, MeNsaaH requested changes

2022-11-08 23:25 UTC, MeNsaaH commented on variables.tf
> +variable "create_ssh_fw_rule" {
Make this `create_ssh_firewall_rule`

2022-11-08 23:25 UTC, MeNsaaH commented on versions.tf
> +  required_providers {
Remove the required providers here. This module is compatible with all versions of google so far

2022-11-09 14:54 UTC, adrianoseie commented on variables.tf
> +variable "create_ssh_fw_rule" {
Sure. done

2022-11-09 23:52 UTC, merged

2022-11-09 23:52 UTC, MeNsaaH commented
This PR is included in version 2.4.0 :tada: